---
- name: Determine target IP
  set_fact:
    target_ip: "{{ hypervisor_ip if hypervisor_ip != '' else ansible_default_ipv4.address }}"

- name: Check current nmcli configuration mode
  # On vérifie si la méthode IPv4 est 'manual' ou 'auto'
  command: "nmcli -g ipv4.method connection show cloudbr0"
  register: cloudbr0_method
  changed_when: false
  failed_when: false

- name: Configure cloudbr0 parameters (Static mode)
  nmcli:
    conn_name: "cloudbr0"
    ifname: "cloudbr0"
    type: bridge
    ip4: "{{ target_ip }}/{{ netmask_prefix }}"
    gw4: "{{ gateway }}"
    dns4: "{{ dns_server }}"
    method4: "manual" # On force le passage en manuel
    state: present
  # On execute si le mode n'est pas "manual" OU si l'IP n'est pas celle attendue
  when: >
    cloudbr0_method.stdout != 'manual' or 
    target_ip not in ansible_facts['cloudbr0']['ipv4']['address'] | default('')
  register: nmcli_config

- name: Apply network changes and restart cloudbr0
  shell: "nmcli con up cloudbr0"
  async: 20
  poll: 0
  # Utilise 'default(false)' pour éviter les erreurs si la variable n'existe pas
  when: nmcli_config.changed | default(false)
